data <- read.table("household_power_consumption.txt", sep = ";")
names(data) <- c("Date", "Time","ActivePower", "ReactivePower", "Voltage","Intensity","Sub_metering_1", "Sub_metering_2","Sub_metering_3")
useful <- subset(data, data$Date == "1/2/2007" | data$Date == "2/2/2007")
datetime <- strptime(paste(useful$Date, useful$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
plot(datetime, as.numeric(useful$Sub_metering_1), type = "l", ylab = "Energy Submetering", xlab = " ")
lines(datetime, as.numeric(useful$Sub_metering_2), type = "l", col = "red")
lines(datetime, as.numeric(useful$Sub_metering_3), type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))